import "./globals.css";
import Provider from "../../utils/Provider";
import { dir } from "i18next";

export const metadata = {
	title: "User management ",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	params: { lng },
}: {
	children: React.ReactNode;
	params: any;
}) {
	return (
		<html lang={lng} dir={dir(lng)} data-theme="nord">
			<body>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
